In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
x = np.random.randint(10, size=5)
x

array([5, 7, 9, 6, 9])

In [4]:
y = np.random.randint(10, size=5)
y

array([8, 7, 1, 7, 3])

In [5]:
x_mean = np.mean(x)
x_mean

7.2

In [6]:
y_mean = np.mean(y)
y_mean

5.2

In [7]:
theta = np.sum((x - x_mean)*(y - y_mean))/np.sum((x - x_mean)**2)
theta

-1.5781250000000002

In [8]:
c = (theta*x) - y
c

array([-15.890625, -18.046875, -15.203125, -16.46875 , -17.203125])